### ISSUE TITLE
Vanilla JS without node modules

### ISSUE THREAD

**Issue by Ishaq74** [maslick/koder-vanilla-js#2]
Hello, i can't get node modules or access to CLI. How to get the full folder please? without installing nothing.

**Comment by maslick** [comment]
You should run:
```
npm i
```
After that, check your `node_modules` directory.

**Comment by Ishaq74** [comment]
So there is no pure vanilla javascript ? I downloaded the full repository with npm then it display "start scan" "stop scan" but show no camera authorisation on iphone or android. only a blank screen after "start scan"

**Comment by maslick** [comment]
What do you mean by "pure" vanilla javascript? Copy paste the code from the `npm` repo and you'll have "pure" vanilla javascript ;)

**Comment by Ishaq74** [comment]
I downloaded the full repository with npm then it display "start scan" "stop scan" but show no camera authorisation on iphone or android. only a blank screen after "start scan"

**Comment by maslick** [comment]
@Ishaq74 see the updated [Readme](https://github.com/maslick/koder-vanilla-js/blob/master/README.md).
This will get you started on your local development PC (e.g. a laptop with a web-camera). If you want to test on a real device, there are 2 options:

* You need to serve your code via `https`
* Deploy your code to any cloud provider e.g. on GCP - they serve `https` by default (see this example https://koder-browser.web.app)
